declare module "*.module.css";
declare module "*.module.scss";
declare module "*.png";
declare module "*.jpg";
declare module "*.svg";
declare module "*.gif";
declare module "i18next";
declare module "react-i18next";
declare module "react-scrollspy-nav";
